# Generated by Django 4.2.9 on 2024-02-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_buku_cover_buku_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kelompok',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
