# Generated by Django 4.2.9 on 2024-02-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_buku_slug_kelompok_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
