# Generated by Django 4.2.9 on 2024-02-17 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_buku_tanggal_remove_buku_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koleksi',
            name='buku',
        ),
        migrations.RemoveField(
            model_name='koleksi',
            name='keterangan',
        ),
        migrations.AddField(
            model_name='buku',
            name='koleksi',
            field=models.ManyToManyField(blank=True, to='app.koleksi'),
        ),
        migrations.AddField(
            model_name='koleksi',
            name='bukus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='koleksi_set', to='app.buku'),
            preserve_default=False,
        ),
    ]
