# Generated by Django 4.2.9 on 2024-02-17 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_remove_koleksi_buku_remove_koleksi_keterangan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='jumlah',
        ),
        migrations.CreateModel(
            name='Pinjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_peminjaman', models.DateField()),
                ('tanggal_pengembalian', models.DateField()),
                ('status', models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan')], max_length=255)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buku')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
