# Generated by Django 4.2.9 on 2024-02-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_pinjam_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjam',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
