# Generated by Django 4.2.9 on 2024-02-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_pinjam_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjam',
            name='ket',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
