# Generated by Django 4.2.9 on 2024-02-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_pinjam_ket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='koleksi',
        ),
        migrations.AddField(
            model_name='koleksi',
            name='ket',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='koleksi',
            name='bukus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buku'),
        ),
    ]
