# Generated by Django 4.2.9 on 2024-02-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_buku_koleksi_koleksi_ket_alter_koleksi_bukus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koleksi',
            name='ket',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
