# Generated by Django 4.2.9 on 2024-02-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_koleksi_ket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koleksi',
            name='ket',
        ),
    ]
