# Generated by Django 4.2.9 on 2024-02-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_koleksi_ket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinjam',
            name='ket',
        ),
    ]
