# Generated by Django 4.2.9 on 2024-02-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_ulasan_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulasan',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
