# Generated by Django 4.2.9 on 2024-02-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_kelompok_bukus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelompok',
            name='bukus',
        ),
        migrations.AlterField(
            model_name='buku',
            name='kelompok_buku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.kelompok'),
            preserve_default=False,
        ),
    ]
