# Generated by Django 4.2.9 on 2024-02-19 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_kelompok_bukus_alter_buku_kelompok_buku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='kelompok_buku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kelompok'),
        ),
    ]
