# Generated by Django 4.2.9 on 2024-02-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='kelompok_buku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.kelompok'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kelompok',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
