# Generated by Django 4.2.9 on 2024-02-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelompok',
            name='slug',
        ),
    ]
